name: 🍺 Set up Homebrew with Tap
description: Set up Homebrew and tap the repository at a specific ref

inputs:
  ref:
    description: The ref to check out
    required: true
  install-bundler-gems:
    description: Whether to install Bundler RubyGems
    required: false
    default: "false"

runs:
  using: composite

  steps:
    - name: 🍺 Set up Homebrew
      id: homebrew
      uses: Homebrew/actions/setup-homebrew@8cc7e0a6e32c01401771864560a5fa13763c9fa2 # master # zizmor: ignore[stale-action-refs]
      env:
        HOMEBREW_IN_CONTAINER: 1

    - name: 🚰 Switch the tap ref
      run: git -C "$tap" switch --detach "$ref"
      shell: bash
      env:
        tap: ${{ steps.homebrew.outputs.repository-path }}
        ref: ${{ inputs.ref }}

    - name: 🫙 Cache Bundler RubyGems
      id: cache
      if: ${{ inputs.install-bundler-gems == 'true' }}
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: ${{ steps.homebrew.outputs.gems-path }}
        key: RubyGems-${{ runner.os }}-${{ steps.homebrew.outputs.gems-hash }}

    - name: 💎 Install Bundler RubyGems
      if: ${{ inputs.install-bundler-gems == 'true' && steps.cache.outputs.cache-hit != 'true' }}
      run: brew install-bundler-gems
      shell: bash
