name: 🍺 Set up Homebrew with Tap
description: Set up Homebrew and tap the repository at a specific ref

inputs:
  ref:
    description: The ref to check out
    required: true

outputs:
  gems-path:
    description: Homebrew's Ruby gems path
    value: ${{ steps.homebrew.outputs.gems-path }}
  gems-hash:
    description: Homebrew's Ruby Gemfile.lock sha256sum
    value: ${{ steps.homebrew.outputs.gems-hash }}

runs:
  using: composite

  steps:
    - name: 🍺 Set up Homebrew
      id: homebrew
      uses: Homebrew/actions/setup-homebrew@87d3af7a72e5ede081b6dafce1798551a74fb366 # master # zizmor: ignore[stale-action-refs]
      env:
        HOMEBREW_IN_CONTAINER: 1

    - name: 🚰 Switch the tap ref
      run: git -C "$tap" switch --detach "$ref"
      shell: bash
      env:
        tap: ${{ steps.homebrew.outputs.repository-path }}
        ref: ${{ inputs.ref }}
