name: 🍺 Set up Homebrew with Tap
description: Set up Homebrew and tap the repository at a specific ref

inputs:
  ref:
    description: The ref to check out
    required: true
  install-bundler-gems:
    description: Whether to install Bundler RubyGems
    required: false
    default: "false"

runs:
  using: composite

  steps:
    - name: 🍺 Set up Homebrew
      id: homebrew
      uses: Homebrew/actions/setup-homebrew@11e37b59b0ec97a638b659c23418c47a7219304e # master # zizmor: ignore[stale-action-refs]
      env:
        HOMEBREW_IN_CONTAINER: 1

    - name: 🚰 Switch the tap ref
      run: git -C "$tap" switch --detach "$ref"
      shell: bash
      env:
        tap: ${{ steps.homebrew.outputs.repository-path }}
        ref: ${{ inputs.ref }}

    - name: 🫙 Cache Bundler RubyGems
      id: cache
      if: ${{ inputs.install-bundler-gems == 'true' }}
      uses: actions/cache@a7833574556fa59680c1b7cb190c1735db73ebf0 # v5.0.0
      with:
        path: ${{ steps.homebrew.outputs.gems-path }}
        key: ${{ runner.os }}-rubygems-${{ steps.homebrew.outputs.gems-hash }}

    - name: 💎 Install Bundler RubyGems
      if: ${{ inputs.install-bundler-gems == 'true' && steps.cache.outputs.cache-hit != 'true' }}
      run: brew install-bundler-gems
      shell: bash
