# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dorg < Formula
  desc "Organize macOS Dock Items"
  homepage "https://github.com/5ouma/dorg"
  version "1.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/5ouma/dorg/releases/download/v1.1.0/dorg_Darwin_x86_64.tar.gz"
    sha256 "83ec0e22117e233fd74422e8cbd813f56c2e719980fae3c5588fbf3505e35dc5"

    def install
      bin.install "dorg"
      generate_completions_from_executable("#{bin}/#{name}", "completion")
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/5ouma/dorg/releases/download/v1.1.0/dorg_Darwin_arm64.tar.gz"
    sha256 "c0960e54327ca5f5392403dfc80de49723b865fbcf9e90c940d3f6b6d7f8a1e0"

    def install
      bin.install "dorg"
      generate_completions_from_executable("#{bin}/#{name}", "completion")
    end
  end

  test do
    system "#{bin}/#{name}", "-v"
  end
end
