# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dorg < Formula
  desc "Organize macOS Dock Items"
  homepage "https://github.com/5ouma/dorg"
  version "1.0.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/5ouma/dorg/releases/download/v1.0.0/dorg_Darwin_x86_64.tar.gz"
    sha256 "8b4a6441772e43a2a68ca50a09c3794cc24bdfa1c950fa11f889b24431a059ba"

    def install
      bin.install "dorg"
      generate_completions_from_executable("#{bin}/#{name}", "completion")
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/5ouma/dorg/releases/download/v1.0.0/dorg_Darwin_arm64.tar.gz"
    sha256 "fe534e5e915ac911360b3ed06b20343db091375f29a10bc26f6b45bb9191f513"

    def install
      bin.install "dorg"
      generate_completions_from_executable("#{bin}/#{name}", "completion")
    end
  end

  test do
    system "#{bin}/#{name}", "-v"
  end
end
