# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mli < Formula
  desc "Manage macOS Login Items"
  homepage "https://github.com/5ouma/mli"
  version "0.5.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/5ouma/mli/releases/download/v0.5.0/mli_Darwin_x86_64.tar.gz"
    sha256 "9fe1584a058ac633bfe6020354a50e87173ce6262259caeab5964412978bcb4c"

    def install
      bin.install "mli"
      generate_completions_from_executable("#{bin}/#{name}", "completion")
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/5ouma/mli/releases/download/v0.5.0/mli_Darwin_arm64.tar.gz"
    sha256 "4f07b4c818daa6665862e74b564e77acf34b5e59c43a26e4e63c566cd64e399b"

    def install
      bin.install "mli"
      generate_completions_from_executable("#{bin}/#{name}", "completion")
    end
  end

  test do
    system "#{bin}/#{name}", "-v"
  end
end
