name: ✨ Bump Packages

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

permissions: {}

jobs:
  bump-formula:
    name: 🧾 Bump Formula
    permissions:
      pull-requests: write
    runs-on: Ubuntu-Latest
    timeout-minutes: 3

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: 🍺 Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@87d3af7a72e5ede081b6dafce1798551a74fb366 # master # zizmor: ignore[stale-action-refs]

      - name: ✨ Version up Homebrew Formula
        uses: dawidd6/action-homebrew-bump-formula@8d494330bce4434918392df134ad3db1167904db # v4
        with:
          token: ${{ secrets.TOKEN }}
          tap: ${{ github.repository }}
          livecheck: true

  bump-cask:
    name: 🥫 Bump Cask
    permissions:
      pull-requests: write
    runs-on: Ubuntu-Latest
    timeout-minutes: 3

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: 🍺 Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@87d3af7a72e5ede081b6dafce1798551a74fb366 # master # zizmor: ignore[stale-action-refs]

      - name: ✨ Version up Homebrew Cask
        uses: macauley/action-homebrew-bump-cask@445c42390d790569d938f9068d01af39ca030feb # v1.0.0
        with:
          token: ${{ secrets.TOKEN }}
          tap: ${{ github.repository }}
          livecheck: true
