name: 🎽 CI

on:
  push:
    branches:
      - main
    paths:
      - "**.rb"
      - .github/workflows/ci.yml
      - .github/workflows/install-package.yml
      - .github/actions/setup-homebrew-with-tap/action.yml
  pull_request:
    paths:
      - "**.rb"
      - .github/workflows/ci.yml
      - .github/workflows/install-package.yml
      - .github/actions/setup-homebrew-with-tap/action.yml
  schedule:
    - cron: 0 0 * * SAT

permissions: {}

jobs:
  test:
    name: 🧪 Test
    runs-on: macOS-Latest
    timeout-minutes: 3

    steps:
      - name: 🚚 Check out repository
        id: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: 🍺 Set up Homebrew with Tap
        id: homebrew
        uses: ./.github/actions/setup-homebrew-with-tap
        with:
          ref: ${{ steps.checkout.outputs.commit }}

      - name: 🧹 Cleanup Test Bot
        run: brew test-bot --verbose --only-cleanup-before

      - name: 🫙 Cache Bundler RubyGems
        id: cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ${{ steps.homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.homebrew.outputs.gems-hash }}

      - name: 💎 Install Bundler RubyGems
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: brew install-bundler-gems

      - name: 💈 Check files for style guidelines
        run: brew style -dv "$GITHUB_REPOSITORY"

      - name: ⚠️ Check if any files have Ruby issues
        run: brew readall -dv "$GITHUB_REPOSITORY"

      - name: 📊 Check for coding style violations
        run: brew audit -dv --strict --tap="$GITHUB_REPOSITORY"

  detect-changed-packages:
    name: 🔍 Detect Changed Packages
    runs-on: Ubuntu-Latest
    timeout-minutes: 1
    outputs:
      packages: ${{ steps.collect.outputs.packages }}

    steps:
      - name: 🚚 Check out repository
        id: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: 🍺 Set up Homebrew with Tap
        uses: ./.github/actions/setup-homebrew-with-tap
        with:
          ref: ${{ steps.checkout.outputs.commit }}

      - name: 🔄 Filter the changed files
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          filters: |
            package: "**.rb"
            workflow: [.github/workflows/ci.yml, .github/workflows/install-package.yml, .github/actions/setup-homebrew-with-tap/action.yml]
          list-files: shell

      - name: 📡 Collect package information
        id: collect
        run: |
          if "$workflowChanged" || "$scheduled"; then
            packages="$(find "$GITHUB_WORKSPACE" -name '**.rb')"
          else
            packages="$changedPackages"
          fi
          for package in $packages; do
            name="$(echo "$package" | xargs basename | sed 's/\.rb$//')"
            full_name="${GITHUB_REPOSITORY/homebrew-}/$name"
            if [[ "$package" =~ Casks ]] || (brew info "$full_name" | grep -q 'Required: macOS'); then
              macos_only="yes"
            fi
            echo "$name,$full_name,$macos_only" | jq -Rc 'split(",") | { name: .[0], full_name: .[1], macos_only: .[2] | test("yes") }'
          done | echo "packages=$(jq -sc)" | tee -a "$GITHUB_OUTPUT"
        env:
          changedPackages: ${{ steps.filter.outputs.package_files }}
          workflowChanged: ${{ steps.filter.outputs.workflow }}
          scheduled: ${{ github.event_name == 'schedule' }}

  install:
    name: 📥 Install ${{ matrix.package.name }}
    needs: detect-changed-packages
    uses: ./.github/workflows/install-package.yml
    with:
      package: ${{ matrix.package.full_name }}
      macos_only: ${{ matrix.package.macos_only }}
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.detect-changed-packages.outputs.packages) }}
