name: 📥 Install Package

on:
  workflow_call:
    inputs:
      package:
        description: The package to install
        required: true
        type: string
      macos_only:
        description: Whether the package is macOS only
        required: true
        type: boolean

permissions: {}

jobs:
  define-os:
    name: 🔍 Define OS
    runs-on: Ubuntu-Slim
    timeout-minutes: 1
    outputs:
      os: ${{ steps.decide-os.outputs.os }}

    steps:
      - name: 🐧 Decide whether to install on Ubuntu
        id: decide-os
        run: |
          os=('macOS-15' 'macOS-15-Intel')
          "$macosOnly" || os+=('Ubuntu-24.04' 'Ubuntu-24.04-ARM')
          echo "os=$(jq -Rc 'split(" ")' <<<"${os[@]}")" | tee -a "$GITHUB_OUTPUT"
        env:
          macosOnly: ${{ inputs.macos_only }}

  install:
    name: ${{ case(startsWith(matrix.os, 'macOS-'), '🍎', startsWith(matrix.os, 'Ubuntu-'), '🐧', '❓') }} ${{ matrix.os }}
    needs: define-os
    runs-on: ${{ matrix.os }}
    timeout-minutes: 3
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(needs.define-os.outputs.os) }}

    steps:
      - name: 🚚 Check out repository
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: 🍺 Set up Homebrew with Tap
        uses: ./.github/actions/setup-homebrew-with-tap
        with:
          ref: ${{ steps.checkout.outputs.commit }}

      - name: 📦 Install package
        run: brew install --verbose "$package"
        env:
          package: ${{ inputs.package }}
          HOMEBREW_NO_SANDBOX_LINUX: 1
